MOEN-ERP/Controllers/SharedController.cs
using AspNetCore;
using DevExpress.ClipboardSource.SpreadsheetML;
using DevExpress.CodeParser;
using DevExpress.Pdf.Native.BouncyCastle.Ocsp;
using DevExpress.PivotGrid.QueryMode;
using DevExpress.XtraCharts.Native;
using DevExpress.XtraRichEdit.Model;
using MOEN_ERP.Models;
using MOEN_ERP.Models.Common;
using MOEN_ERP.Models.Data;
using MOEN_ERP.Models.RawData;
using MOEN_ERP.Models.ViewModel;
using MOEN_ERP.Models.ViewModel.AudioVisualServiceRequest;
using MOEN_ERP.Models.ViewModel.CateringServiceRequest;
using MOEN_ERP.Models.ViewModel.ConferenceBooking;
using MOEN_ERP.Models.ViewModel.ExpensesRequest;
using MOEN_ERP.Models.ViewModel.MeetingRoomBooking;
using MOEN_ERP.Models.ViewModel.VehicleBooking;
using MOEN_ERP.Models.ViewModel.VehicleGatePassTicket;
using MOEN_ERP.Models.ViewModel.VehicleQueueData;
using MOEN_ERP.Models.ViewModel.VehicleRecord;
using MOEN_ERP.Models.ViewModel.VideoConferenceBooking;
using MOEN_ERP.Services;
using MOEN_ERP.Services.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Org.BouncyCastle.Bcpg.OpenPgp;
using Org.BouncyCastle.Ocsp;
using SkiaSharp;
using System.Net.Http.Headers;
using MOEN_ERP.DAL.Models;

namespace MOEN_ERP.Controllers
{
    [Authorize]
    public class SharedController : Controller
    {
        private readonly IMasterService _masterData;
        private readonly IRawDataService _rawData;
        private readonly IDataService _data;
        //private readonly ILogger _logger;
        private readonly IAttachFileService _attachFile;
        private readonly IDropdowns _dropdowns;
        private readonly IVehicleNotificationsService _vehicleNoti;
        private readonly IMeetingNotificationsService _meetingNoti;
        public SharedController(IMasterService masterData,
            IRawDataService rawData,
            IDataService data,
            IAttachFileService attachFile,
            IDropdowns dropdowns,
            IVehicleNotificationsService vehicleNoti,
             IMeetingNotificationsService meetingNoti
            )
        {
            //_logger = logger;
            _masterData = masterData;
            _rawData = rawData;
            _data = data;
            _attachFile = attachFile;
            _dropdowns = dropdowns;
            _vehicleNoti = vehicleNoti;
            _meetingNoti = meetingNoti;
        }

        #region Json Results
        [HttpGet]
        public async Task<IActionResult> GetVehicle(int pVehicleId)
        {
            var res = await _rawData.GetViewVehicleAsync(pVehicleId);
            return Json(res);
        }

        [HttpGet]
        public async Task<IActionResult> GetOfficer(int pId)
        {
            var res = await _rawData.GetViewOfficerAsync(pId);
            return Json(res);
        }

        [HttpPost]
        public async Task<IActionResult> GetViewMeetingRoomDevice(VMeetingRoomDevice sch)
        {
            var res = await _rawData.GetViewMeetingRoomDeviceListAsync(sch);
            return Json(res);
        }

        [HttpPost]
        public async Task<IActionResult> GetViewMeetingRoomDeviceGroup(VMeetingRoomDevice sch)
        {
            var dataRoomDeviceList = await _rawData.GetViewMeetingRoomDeviceListAsync(sch);
            var res = (from t in dataRoomDeviceList
                       group t by new
                       {
                           t.MeetingRoomId,
                           t.DeviceId,
                       }
                                      into grp
                       select new VMeetingRoomDevice
                       {
                           MeetingRoomId = grp.Key.MeetingRoomId,
                           DeviceId = grp.Key.DeviceId,
                           DeviceName = grp?.FirstOrDefault()?.DeviceName,
                           Detail = grp?.FirstOrDefault()?.Detail,
                           UsedPerRoom = grp?.FirstOrDefault()?.UsedPerRoom,
                           TotalAll = grp?.FirstOrDefault()?.TotalAll,
                           TotalRemain = grp?.FirstOrDefault()?.TotalRemain,
                           TotalUsedAll = grp?.FirstOrDefault()?.TotalUsedAll,
                           StatusName = string.Join(", ", grp.Select(x => x.StatusName)),
                       }).FirstOrDefault();
            //--Return 1 Data
            if (res == null)
            {
                var deviceRoom = await _data.GetMeetingRoomDeviceListAsync(new MeetingRoomDevice { DeviceId = sch.DeviceId });
                if (deviceRoom.Count() > 0)
                {
                    res = new VMeetingRoomDevice()
                    {
                        MeetingRoomId = sch.MeetingRoomId,
                        DeviceId = sch.DeviceId,
                        
                        TotalUsedAll = deviceRoom.Count(),
                        UsedPerRoom = 0,
                        TotalAll = (await _data.GetAudioVisualDeviceAsync(sch.DeviceId ?? 0)).TotalAll ?? 0,
                    };
                    res.TotalRemain = res.TotalAll - res.TotalUsedAll;

                }

            }
            return Json(res);
        }

        [HttpPost]
        public async Task<IActionResult> GetAudioVisualDevice(AudioVisualDevice sch)
        {
            var res = await _data.GetAudioVisualDeviceAsync((int)sch?.Id);
            return Json(res);
        }
        #endregion

        public IActionResult VehicalModalEventPreviewBooking(MockupViewModel sch)
        {
            MockupViewModel data = new MockupViewModel();
            data.FormType = sch.FormType;
            data.ActionType = sch.ActionType;
            return PartialView("Partialviews/Vehicle/_ModalEventPreviewBooking", data);
        }

        public IActionResult VehicalModalEventPreviewBookingConfirm()
        {
            return PartialView("Partialviews/Vehicle/_ModalEventPreviewBookingConfirm");
        }

        public IActionResult VehicalModalEventPreviewBookingRefuse()
        {
            return PartialView("Partialviews/Vehicle/_ModalEventPreviewBookingRefuse");
        }


        #region Vehicle
        public async Task<IActionResult> RelateVehicleBrand()
        {
            MasterVehicleBrand sch = new MasterVehicleBrand()
            {
                Active = true,
            };
            return Json(await _masterData.GetMasterVehicleBrandList(sch));
        }

        public async Task<IActionResult> RelateVehicleModel(int vehicleBrandId)
        {
            var results = new List<SelectListItem>();
            MasterVehicleModel sch = new MasterVehicleModel();

            sch.Active = true;
            if (vehicleBrandId > 0) sch.VehicleBrandId = vehicleBrandId;

            return Json(await _masterData.GetMasterVehicleModelList(sch));
        }

        public async Task<IActionResult> RelateConferenceLicense(int conferenceId)
        {
            MasterVideoConferenceLicense sch = new MasterVideoConferenceLicense();
            sch.Active = true;
            if (conferenceId > 0) sch.ConferenceId = conferenceId;

            return Json(await _masterData.GetMasterVideoConferenceLicenseListAsync(sch));

        }



        //public async Task<IActionResult> RelateVehicleForAssign(int VehicleBookingId, int VehicleTypeId)
        //{
        //    var res = await _rawData.GetSPVehicleForAssignListAsync(VehicleBookingId);
        //    var data = JsonConvert.DeserializeObject<List<Vehicle>>((string)res.Data);
        //    if (VehicleTypeId > 0)
        //    {
        //        data = data.Where(x => x.VehicleTypeId == VehicleTypeId).ToList();
        //    }

        //    return Json(data);
        //}

        [HttpGet]
        public async Task<IActionResult> RelateDriverForAssign(string travelFromDateValue, string travelToDateValue)
        {
            DateTime fromDate = new DateTime(1, 1, 1);
            DateTime toDate = new DateTime(1, 1, 1);
            if (!string.IsNullOrEmpty(travelFromDateValue))
            {
                string[] fromDateArg = travelFromDateValue.Split('/');
                fromDate = new DateTime(Convert.ToInt32(fromDateArg[2]) - 543, Convert.ToInt32(fromDateArg[1]), Convert.ToInt32(fromDateArg[0]));
            }
            if (!string.IsNullOrEmpty(travelToDateValue))
            {
                string[] toDateArg = travelToDateValue.Split('/');
                toDate = new DateTime(Convert.ToInt32(toDateArg[2]) - 543, Convert.ToInt32(toDateArg[1]), Convert.ToInt32(toDateArg[0]));
            }

            SearchDriverListForAssign shc = new SearchDriverListForAssign
            {
                TravelFromDate = fromDate,
                TravelToDate = toDate,
            };

            var res = new List<VOfficer>();
            var resData = await _rawData.GetDriverListForAssignAsync(shc);
            if (resData.Type == ApiResultsType.success.ToString())
            {
                res = JsonConvert.DeserializeObject<List<VOfficer>>((string)resData.Data);
            }
            return Json(res);
        }




        [HttpGet]
        public async Task<IActionResult> RelateVehicleForAssign(string travelFromDateValue, string travelToDateValue, int vehicleTypeValue)
        {
            DateTime fromDate = new DateTime(1, 1, 1);
            DateTime toDate = new DateTime(1, 1, 1);
            if (!string.IsNullOrEmpty(travelFromDateValue))
            {
                string[] fromDateArg = travelFromDateValue.Split('/');
                fromDate = new DateTime(Convert.ToInt32(fromDateArg[2]) - 543, Convert.ToInt32(fromDateArg[1]), Convert.ToInt32(fromDateArg[0]));
            }
            if (!string.IsNullOrEmpty(travelToDateValue))
            {
                string[] toDateArg = travelToDateValue.Split('/');
                toDate = new DateTime(Convert.ToInt32(toDateArg[2]) - 543, Convert.ToInt32(toDateArg[1]), Convert.ToInt32(toDateArg[0]));
            }

MOEN-ERP/Views/Shared/Partialviews/_DisplayAttachFileList.cshtml
@model List<MOEN_ERP.DAL.Models.AttachFile>

@if (Model.Count > 0)
{
    int row = 1;
    @foreach (var item in Model)
    {
        if (row == 1)
        {
            <a class="link-primary text-hover-dark" href="javascript:void;" onclick="window.open('@Url.Action("ViewAttachFile", "AttachFile", new { @id = item.RowGuid, refTable=item.ReferenceTable, refCmp=item.ReferenceGroup })', '_blank');">
                @item.Filename
            </a>
        }
        else
        {
            <br />

            <a class="link-primary text-hover-dark" href="javascript:void;" onclick="window.open('@Url.Action("ViewAttachFile", "AttachFile", new { @id = item.RowGuid, refTable=item.ReferenceTable, refCmp=item.ReferenceGroup })', '_blank');">
                @item.Filename
            </a>
        }

        row++;
    }
}
@*else
{
    <div>-</div>
}*@

MOEN-ERP/Views/Shared/Partialviews/_DisplayAttachFileListByRef.cshtml
@*@model Model.*@

<div id="divModalSelectSnackAtttachResults_@Model">

</div>


<script>
    
    $(function(){
        
        var url = '@Url.Action("GetAttachFileListByRef","Shared")';
      
            $.get(url, {
                ReferenceId: '@Model',
                ReferenceTable: 'CateringRestaurant',
                ReferenceGroup: 'CateringRestaurant'
            }).done(function (res) {
            $('#divModalSelectSnackAtttachResults_@Model').html(res);
            });   

    });

</script>

MOEN-ERP/Views/Shared/Partialviews/_DisplayAttachFileListByRefResults.cshtml
@model List<MOEN_ERP.DAL.Models.AttachFile>

@if (Model.Count > 0)
{
    int row = 1;
    @foreach (var item in Model)
    {
        if (row == 1)
        {
            <a class="link-primary text-hover-dark" href="javascript:void;" onclick="window.open('@Url.Action("ViewAttachFile", "AttachFile", new { @id = item.RowGuid, refTable=item.ReferenceTable, refCmp=item.ReferenceGroup })', '_blank');">
                @item.Filename
            </a>
        }
        else
        {
            <br />

            <a class="link-primary text-hover-dark" href="javascript:void;" onclick="window.open('@Url.Action("ViewAttachFile", "AttachFile", new { @id = item.RowGuid, refTable=item.ReferenceTable, refCmp=item.ReferenceGroup })', '_blank');">
                @item.Filename
            </a>
        }

        row++;
    }
}

MOEN-ERP/Views/Shared/Partialviews/_ModalApporve.cshtml
@model MOEN_ERP.Models.MockupViewModel
@{
    var actionType = Model.ActionType;
    var formType = Model.FormType;
}


<div class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" id="modalManageVDOConferences">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">

                @if (formType == "room")
                {
                    <h3 class="modal-title"><span class="btn btn-icon bg-success"><i class="fa fa-check"></i></span> อนุมัติการจองห้องประชุม</h3>
                }

                <!--begin::Close-->
                <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal" aria-label="Close">
                    <i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i>
                </div>
                <!--end::Close-->
            </div>

            <div class="modal-body">

                <div class="row mb-3">
                    <label class="col-form-label col-xxl-12 col-xl-12 col-lg-12 col-md-12 col-sm-12">ความคิดเห็น <span class="required"></span> : </label>
                    
                </div>

                <div class="row mb-3">                  
                    <div class="col-xxl-12 col-xl-12 col-lg-12 col-md-12 col-sm-12">
                        <textarea class="form-control form-control-sm" rows="4"></textarea>
                    </div>
                </div>
               
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-primary">ยืนยัน</button>
                <button type="button" class="btn btn-light" data-bs-dismiss="modal">ยกเลิก</button>
            </div>
        </div>
    </div>
</div>

MOEN-ERP/Views/Shared/Partialviews/_ModalApproveServiceRequests.cshtml
@model MOEN_ERP.Models.MockupViewModel
@{
    var actionType = Model.ActionType;
}
<div class="modal fade" id="modal-Preview" tabindex="-1" role="dialog" aria-labelledby="modalUploadMultiple" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                @if (actionType == "audiovisual-audiovisual-service" || actionType == "audiovisual-approve-service-requests")
                {
                    <h5 class="modal-title">อนุมัติการขอใช้บริการโสตทัศน์</h5>
                }
                else if (actionType == "catering-approve-service-requests")
                {
                    <h5 class="modal-title">อนุมัติการขอใช้บริการจัดเลี้ยง</h5>
                }
                else if (actionType == "catering-audiovisual-service")
                {
                    <h5 class="modal-title">ยืนยันการขอใช้บริการจัดเลี้ยง</h5>
                }
                else if (actionType == "consider-booking-list")
                {
                    <h5 class="modal-title">อนุมัติการจองห้องประชุม</h5>
                }
                else if (actionType == "approve-carbooking")
                {
                    <h5 class="modal-title">อนุมัติการจองยานพาหนะ</h5>
                }
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <div class="form-group">

                    @* <iframe name="Preview" id="Preview" src="~/PDF/แบบฟอร์มขอใช้บริการงานโสต.pdf" onload="hideWait();" style="width: 100%; height: 800px;">
                    </iframe>*@
                    @if (actionType == "audiovisual-audiovisual-service" || actionType == "audiovisual-approve-service-requests")
                    {
                        <iframe name="Preview" id="Preview" src="~/PDF/แบบฟอร์มขอใช้บริการงานโสต.pdf" onload="hideWait();" style="width: 100%; height: 800px;">
                        </iframe>
                    }
                    else if (actionType == "catering-approve-service-requests" || actionType == "catering-audiovisual-service" || actionType == "consider-booking-list")
                    {
                        <iframe name="Preview" id="Preview" src="~/PDF/แบบขอใช้บริการจัดเลี้ยง.pdf" onload="hideWait();" style="width: 100%; height: 800px;">
                        </iframe>
                    }
                    else if (actionType == "approve-carbooking")
                    {
                        <iframe name="Preview" id="Preview" src="~/PDF/ขออนุญาตใช้รถยนต์.pdf" onload="hideWait();" style="width: 100%; height: 800px;">
                        </iframe>
                    }

                </div>
                <h5 class="mb-5">ประวัติการพิจารณา</h5>

                <div class="table-responsive-xxl table-responsive-xl table-responsive-lg table-responsive-md">
                    @if (actionType == "audiovisual-audiovisual-service" || actionType == "audiovisual-approve-service-requests")
                    {
                        <table id="table1" class="table table-row-dashed table-row-gray-300 align-middle gy-5 gs-7 js-table">
                            <thead class="table-primary">
                                <tr class="fw-semibold fs-6 text-gray-80">
                                    <th>วันที่</th>
                                    <th>ผู้พิจารณา</th>
                                    <th>ผู้พิจารณาลำดับถัดไป</th>
                                    <th>การพิจารณา</th>
                                    <th>ความคิดเห็น</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>03/06/2566 10:00</td>
                                    <td>นายเจ้าหน้าที่ส่วนงานพัสดุ</td>
                                    <td></td>
                                    <td>อนุมัติให้ดำเนินการ</td>
                                    <td>เห็นควรดำเนินการ</td>
                                </tr>
                                <tr>
                                    <td>02/06/2566 08:00</td>
                                    <td>นายทดสอบ จองห้องประชุม</td>
                                    <td>นายเจ้าหน้าที่ ส่วนงานพัสดุ</td>
                                    <td>ส่งเรื่องพิจารณา</td>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    }
                    else if (actionType == "catering-approve-service-requests" || actionType == "catering-audiovisual-service" || actionType == "consider-booking-list")
                    {
                        <table id="table1" class="table table-row-dashed table-row-gray-300 align-middle gy-5 gs-7 js-table">
                            <thead class="table-primary">
                                <tr class="fw-semibold fs-6 text-gray-80">
                                    <th>วันที่</th>
                                    <th>ผู้พิจารณา</th>
                                    <th>ผู้พิจารณาลำดับถัดไป</th>
                                    <th>การพิจารณา</th>
                                    <th>ความคิดเห็น</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>03/06/2566 10:00</td>
                                    <td>นายเจ้าผู้อำนวยการ สก.</td>
                                    <td>นายเจ้าหน้าที่ ฝ่ายจัดเลี้ยง</td>
                                    <td>อนุมัติให้ดำเนินการ</td>
                                    <td>เห็นควรดำเนินการ</td>
                                </tr>
                                <tr>
                                    <td>02/06/2566 08:00</td>
                                    <td>นายทดสอบ ขอใช้บริการ</td>
                                    <td>นายเจ้าผู้อำนวยการ สก.</td>
                                    <td>ส่งเรื่องพิจารณา</td>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    }
                    else if (actionType == "approve-carbooking")
                    {
                        <table id="table1" class="table table-row-dashed table-row-gray-300 align-middle gy-5 gs-7 js-table">
                            <thead class="table-primary">
                                <tr class="fw-semibold fs-6 text-gray-80">
                                    <th>วันที่</th>
                                    <th>ผู้พิจารณา</th>
                                    <th>ผู้พิจารณาลำดับถัดไป</th>
                                    <th>การพิจารณา</th>
                                    <th>ความคิดเห็น</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>03/06/2566 10:00</td>
                                    <td>นายเจ้าหน้าที่ ส่วนงานพัสดุ</td>
                                    <td></td>
                                    <td>อนุมัติให้ดำเนินการ</td>
                                    <td>เห็นควรดำเนินการ</td>
                                </tr>
                                <tr>
                                    <td>02/06/2566 08:00</td>
                                    <td>นายทดสอบ จองยานพาหนะ</td>
                                    <td>นายเจ้าหน้าที่ ส่วนงานพัสดุ</td>
                                    <td>ส่งเรื่องพิจารณา</td>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    
                    }
                </div>

            </div>
            <div class="modal-footer d-flex justify-content-between">
                @if (actionType == "audiovisual-audiovisual-service" || actionType == "catering-audiovisual-service")
                {
                    <div>
                        <button class="btn btn-sm btn-secondary" data-bs-dismiss="modal"><i class="fa fa-chevron-left"></i> กลับหน้ารายการ</button>
                    </div>
                    <div>
                    </div>
                    <div>
                        <button type="button" class="btn btn-sm btn-success" data-bs-dismiss="modal"><i class="fas fa-check"></i> ดำเนินการแล้ว</button>
                    </div>
                }
                else if (actionType == "audiovisual-approve-service-requests" || actionType == "catering-approve-service-requests" || actionType == "consider-booking-list")
                {
                    <div>
                        <button class="btn btn-sm btn-secondary" data-bs-dismiss="modal"><i class="fa fa-chevron-left"></i> กลับหน้ารายการ</button>
                    </div>
                    <div>
                    </div>
                    <div>
                        <button data-url="@Url.Action("EventServiceRequest", "Consider",new {actypeType = "approve", formType = "room"})" data-toggle="ajax-modal-servicerequest" class="btn btn-sm btn-success" data-bs-dismiss="modal"><i class="fa fa-check"></i> อนุมัติ</button>
                        <button data-url="@Url.Action("EventServiceRequest", "Consider",new {actypeType = "dis-approval", formType = "room"})" data-toggle="ajax-modal-servicerequest" class="btn btn-sm btn-danger" data-bs-dismiss="modal"><i class="fa fa-close"></i> ไม่อนุมัติ</button>
                    </div>
                }
                 else if (actionType == "approve-carbooking")
                {
                    <div>
                        
                    </div>
                    <div>
                    </div>
                    <div>
                        <button data-url="@Url.Action("EventServiceRequest", "Consider",new {actypeType = "approve", formType = "car"})" data-toggle="ajax-modal-servicerequest" class="btn btn-sm btn-success" data-bs-dismiss="modal"><i class="fa fa-check"></i> อนุมัติ</button>
                        <button data-url="@Url.Action("EventServiceRequest", "Consider",new {actypeType = "dis-approval", formType = "car"})" data-toggle="ajax-modal-servicerequest" class="btn btn-sm btn-danger" data-bs-dismiss="modal"><i class="fa fa-close"></i> ไม่อนุมัติ</button>
                        <button data-url="@Url.Action("EventServiceRequest", "Consider",new {actypeType = "sendback-edit", formType = "car"})" data-toggle="ajax-modal-servicerequest" class="btn btn-sm btn-warning" data-bs-dismiss="modal"><i class="fa fa-reply"></i> ส่งกลับแก้ไข</button>
                        <button class="btn btn-sm btn-secondary" data-bs-dismiss="modal">กลับหน้ารายการ</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<div id="divModalApprove"></div>

<script>
    $(function () {

        var divModalApprove = $('#divModalApprove');

        $('button[data-toggle="ajax-modal-servicerequest"]').click(function () {
            var url = $(this).data('url');
            $.get(url).done(function (data) {
                divModalApprove.html(data);
                divModalApprove.find('.modal').modal('show');
            });
        });

    });
</script>

MOEN-ERP/Views/Shared/Partialviews/_ModalDisApproval.cshtml
@model MOEN_ERP.Models.MockupViewModel
@{
    var actionType = Model.ActionType;
    var formType = Model.FormType;
}


<div class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" id="modalManageVDOConferences">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">

                @if (formType == "room")
                {
                    <h3 class="modal-title"><span class="btn btn-icon bg-danger"><i class="fa fa-close"></i></span> ไม่อนุมัติการจองห้องประชุม</h3>
                }
                <!--begin::Close-->
                <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal" aria-label="Close">
                    <i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i>
                </div>
                <!--end::Close-->
            </div>

            <div class="modal-body">
                <div class="row mb-3">
                    <label class="col-form-label col-xxl-12 col-xl-12 col-lg-12 col-md-12 col-sm-12">ความคิดเห็น <span class="required"></span> : </label>

                </div>
                <div class="row mb-3">                  
                    <div class="col-xxl-12 col-xl-12 col-lg-12 col-md-12 col-sm-12">
                        <textarea class="form-control form-control-sm" rows="4"></textarea>
                    </div>
                </div>

            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-primary">ยืนยัน</button>
                <button type="button" class="btn btn-light" data-bs-dismiss="modal">ยกเลิก</button>
            </div>
        </div>
    </div>
</div>

MOEN-ERP/Views/Shared/Partialviews/_ModalSelectConsidersRequest.cshtml
<div class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" id="modalManageVDOConferences">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">เลือกผู้พิจารณาคำขอใช้ยานพาหนะ</h3>
                <!--begin::Close-->
                <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal" aria-label="Close">
                    <i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i>
                </div>
                <!--end::Close-->
            </div>

            <div class="modal-body">

                <div class="row mb-3">
                    <label class="col-form-label col-xxl-3 col-xl-3 col-lg-3 col-md-3 col-sm-12">ผู้พิจารณา <span class="required"></span> : </label>
                    <div class="col-xxl-9 col-xl-9 col-lg-9 col-md-9 col-sm-12">
                        <seelct class="form-control form-select form-select-sm">
                            <option>กรุณาเลือก</option>
                        </seelct>
                    </div>
                </div>

            </div>

            <div class="modal-footer">
                <button id="btnSubmit" type="button" class="btn btn-primary">ยืนยัน</button>
                <button type="button" class="btn btn-light" data-bs-dismiss="modal">ยกเลิก</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(function(){

        $('#btnSubmit').click(function () {
            Swal.fire({ title: 'บันทึกข้อมูลสำเร็จ', text: '', icon: 'success', confirmButtonText: 'ตกลง', confirmButtonColor: '#3B9EF8', allowOutsideClick: false, allowEscapeKey: false, })
                .then((result) => {
                    if (result.isConfirmed) {
                        location.reload();
                    }
                });
        });

    });
</script>