MOEN-ERP/Controllers/MasterController.cs
using DevExpress.ClipboardSource.SpreadsheetML;
using DevExpress.XtraRichEdit.Import.Html;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using MOEN_ERP.DAL.Models;
using MOEN_ERP.Models.Common;
using MOEN_ERP.Models.RawData;
using MOEN_ERP.Models.ViewModel;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;

namespace MOEN_ERP.Controllers
{
    public class MasterController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly SettingsModel _settingsModels;
        public MasterController(HttpClient httpClient, IOptions<SettingsModel> option)
        {
            _httpClient = httpClient;
            _settingsModels = option.Value;
        }


        #region 1.MasterAssetType
        public IActionResult MasterAssetType()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> MasterAssetType(string? NameThai, bool? Active)
        {
            var data = new List<VMasterAssetType>();
            var response = await _httpClient.GetAsync(_settingsModels.BaseUrlApi + $"/Master/GetListVMasterAssetType?nameThai={NameThai}&Active={Active}");
            if (response.IsSuccessStatusCode)
            {
                var json = await response.Content.ReadAsStringAsync();
                data = JsonConvert.DeserializeObject<List<VMasterAssetType>>(json) ?? new List<VMasterAssetType>();
            }
            return PartialView("_tableMasterAssetType", data.OrderBy(x=>x.SequenceNumber).ToList());
        }

        [HttpPost]
        public async Task<IActionResult> MasterAssetTypeDetail(int? AssetTypeId, bool? success, string? error)
        {
            var data = new MasterAssetTypeDetailModel();
            data.MasterAssetType = new MasterAssetType();
            data.ListMasterAssetTypeSub = new List<MasterAssetTypeSub>();
           
            if (AssetTypeId != 0)
            {
                var response2 = await _httpClient.GetAsync(_settingsModels.BaseUrlApi + $"/Master/GetMasterAssetType?Id={AssetTypeId}");
                if (response2.IsSuccessStatusCode)
                {
                    var json = await response2.Content.ReadAsStringAsync();
                    data = JsonConvert.DeserializeObject<MasterAssetTypeDetailModel>(json) ?? new MasterAssetTypeDetailModel();
                }
              
            }
            if (success != null)
            {
                if (success == true) ViewBag.success = "บันทึกสำเร็จ";
                else ViewBag.error = error;
            }

            data.listDelSubId = "0";
            return PartialView("_modalMasterAssetType", data);
        }


        [HttpPost]
        public async Task<IActionResult> SaveNewAssetTypeNotHideModal(string pCode, Boolean pActive, string pNameThai, int pLifeTimeDepreciation, Decimal pDepreciation, int pLifeTimeUse, int pSequenceNumber, DateTime pEffectiveFromDate, DateTime pEffectiveToDate) 
        {
            MasterAssetTypeDetailModel newData = new MasterAssetTypeDetailModel();
            newData.MasterAssetType = new MasterAssetType();
            newData.ListMasterAssetTypeSub = new List<MasterAssetTypeSub>();

            newData.MasterAssetType.Id = 0;
            newData.MasterAssetType.Code = pCode;
            newData.MasterAssetType.Active = pActive;
            newData.MasterAssetType.NameThai = pNameThai;
            newData.MasterAssetType.LifeTimeDepreciation = pLifeTimeDepreciation;
            newData.MasterAssetType.Depreciation = pDepreciation;
            newData.MasterAssetType.LifeTimeUse = pLifeTimeUse;
            newData.MasterAssetType.SequenceNumber = pSequenceNumber;            
            newData.MasterAssetType.EffectiveFromDate = pEffectiveFromDate;                
            newData.MasterAssetType.EffectiveToDate = pEffectiveToDate;           

            var user = new Appz(HttpContext).CurrentSignInUser;
            if (newData.MasterAssetType.Active == null) newData.MasterAssetType.Active = false;
            if (newData.MasterAssetType.Id == 0)
            {
                newData.MasterAssetType.CreateBy = user.User.Id;
                newData.MasterAssetType.CreateOn = DateTime.Now;

            }
            else
            {
                newData.MasterAssetType.UpdateBy = user.User.Id;
                newData.MasterAssetType.UpdateOn = DateTime.Now;
            }

            //Check Duplicate : Code
            var data = new List<VMasterAssetType>();
            var response1 = await _httpClient.GetAsync(_settingsModels.BaseUrlApi + $"/Master/GetListVMasterAssetType?");
            Boolean checkDuplicate = false;
            if (response1.IsSuccessStatusCode)
            {
                var json1 = await response1.Content.ReadAsStringAsync();
                data = JsonConvert.DeserializeObject<List<VMasterAssetType>>(json1) ?? new List<VMasterAssetType>();

                if (newData.MasterAssetType.Code != null)
                {
                    string? codeData = newData.MasterAssetType.Code;
                    checkDuplicate = data.Exists(x => x.Code == codeData);

                    if (checkDuplicate == true)
                    {
                        checkDuplicate = false;
                        if (newData.MasterAssetType.Id != 0) // Edit Mode
                        {
                            var item = new VMasterAssetType();
                            item = data.FirstOrDefault(x => x.Code == codeData);
                            if (item != null && item.Id != newData.MasterAssetType.Id)
                            {
                                checkDuplicate = true;
                                ViewBag.error = "Code is duplicated.";
                            }
                        }
                        else
                        {
                            checkDuplicate = true;
                            ViewBag.error = "Code is duplicated.";
                        }
                    }
                }

            }

            //Check Duplicate : SequenceNumber       
            if (checkDuplicate == false)
            {
                if (response1.IsSuccessStatusCode)
                {
                    var json1 = await response1.Content.ReadAsStringAsync();
                    data = JsonConvert.DeserializeObject<List<VMasterAssetType>>(json1) ?? new List<VMasterAssetType>();

                    if (newData.MasterAssetType.SequenceNumber != null)
                    {
                        int? seqData = newData.MasterAssetType.SequenceNumber;
                        checkDuplicate = data.Exists(x => x.SequenceNumber == seqData);

                        if (checkDuplicate == true)
                        {
                            checkDuplicate = false;
                            if (newData.MasterAssetType.Id != 0) // Edit Mode
                            {
                                var item = new VMasterAssetType();
                                item = data.FirstOrDefault(x => x.SequenceNumber == seqData);
                                if (item != null && item.Id != newData.MasterAssetType.Id)
                                {
                                    checkDuplicate = true;
                                    ViewBag.error = "SequenceNumber is duplicated.";
                                }
                            }
                            else
                            {
                                checkDuplicate = true;
                                ViewBag.error = "SequenceNumber is duplicated.";
                            }
                        }
                    }

                }
            }

            int? pAssetTypeId = 0;
            Boolean pSuccess = false;
            string pMessage = string.Empty;

            if (checkDuplicate == false)
            {
                var objMasterAssetType = new MasterAssetType();
                objMasterAssetType = newData.MasterAssetType;
                var json = JsonConvert.SerializeObject(objMasterAssetType);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                var response = await _httpClient.PostAsync(_settingsModels.BaseUrlApi + "/Master/SaveMasterAssetType", content);
                if (response.IsSuccessStatusCode)
                {
                    var result = await response.Content.ReadAsStringAsync();
                    var apiResults = JsonConvert.DeserializeObject<ApiResultsModel>(result) ?? new ApiResultsModel();
                    if (apiResults.Success)
                    {
                        ViewBag.success = "บันทึกสำเร็จ";
                        pAssetTypeId = apiResults.Id;
                        pSuccess = apiResults.Success;
                        pMessage = apiResults.Message;
                    }
                       
                    else ViewBag.error = apiResults.Message;
                }
            }

            MasterAssetTypeDetailModel newResult = new MasterAssetTypeDetailModel();
            newResult.MasterAssetType = new MasterAssetType();
           

            var resultdata = new MasterAssetTypeDetailModel();
            if (pAssetTypeId != 0)
            {
                var response2 = await _httpClient.GetAsync(_settingsModels.BaseUrlApi + $"/Master/GetMasterAssetType?Id={pAssetTypeId}");
                if (response2.IsSuccessStatusCode)
                {
                    var json1 = await response2.Content.ReadAsStringAsync();
                    resultdata = JsonConvert.DeserializeObject<MasterAssetTypeDetailModel>(json1) ?? new MasterAssetTypeDetailModel();
                }
            }

            //newResult.ListMasterAssetTypeSub = new List<MasterAssetTypeSub>();
            //ViewBag.hideModal = "mdlMasterAssetType";

MOEN-ERP/Views/Master/MasterAssetType.cshtml
@section Title {
    <span class="fs-1 fw-semibold">หมวดหมู่ครุภัณฑ์</span>

}
@section Breadcrumb {
    <li class="breadcrumb-item pe-3"><a href="#" class="pe-3">หน้าแรก</a></li>
    <li class="breadcrumb-item pe-3 text-muted">หมวดหมู่ครุภัณฑ์</li>
}

<style>
    .modal + .modal {
        background: rgba(0, 0, 0, 0.6);
    }
</style>

<div class="card">
    <div class="card-header align-items-center py-5 gap-2 gap-md-5">
        <div class="card-title">
            <div class="d-flex align-items-center position-relative my-1">
                <h2>ค้นหา&nbsp;&nbsp;</h2>
                <input id="btnFilter" onclick="showHideFilter()" type="button" style="border:unset; font-size:x-small;" value="แสดง"></input><button style="border:unset; font-size:x-small;" onclick=" showHideFilter()"> <i class="fas fa-angle-down"></i></button>
            </div>
        </div>
        <div class="card-toolbar flex-row-fluid justify-content-end gap-5">
            <a class="btn btn-success btn-sm"
               data-ajax="true"
               data-ajax-method="POST"
               data-ajax-mode="replace"
               data-ajax-update="#mdlDetail"
               href='@Url.Action("MasterAssetTypeDetail", "Master")'>
                <i class="fa fa-plus"></i> สร้างใหม่
            </a>
        </div>
    </div>

    <div class="card-body" id="divFilter" style="display: none;">
        @using (Html.AjaxBeginForm("MasterAssetType", "Master", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "tbl" }, new { enctype = "multipart/form-data", id = "searchForm" }))
        {      

            <div class="row mb-3" >
                <div class="row col-md-6 mb-3">
                    <div class="col-4 text-end">
                        <label class="col-form-label">ชื่อหมวดหมู่ครุภัณฑ์</label>
                    </div>
                    <div class="col-8 text-end">
                        <input class="form-control form-control-sm" name="NameThai" />
                    </div>
                </div>

                <div class="row col-md-6 mb-3 align-items-center">
                    <div class="col-4 text-end">
                        <label class="col-form-label">สถานะการใช้งาน</label>
                    </div>
                    <div class="col-8">
                        <div class="row fv-row">
                            <div class="d-xxl-flex d-xl-flex d-lg-flex d-md-flex d-sm-flex">
                                <div class="form-check form-check-custom form-check-solid me-xxl-10 me-xl-10 me-lg-10 me-md-10 me-sm-10">
                                    <input class="form-check-input" type="radio" value="true" name="Active" checked>
                                    <label class="form-check-label">
                                        ใช้งาน
                                    </label>
                                </div>
                                <div class="form-check form-check-custom form-check-solid me-xxl-10 me-xl-10 me-lg-10 me-md-10 me-sm-10">
                                    <input class="form-check-input" type="radio" value="false" name="Active">
                                    <label class="form-check-label">
                                        ไม่ใช้งาน
                                    </label>
                                </div>
                                <div class="form-check  form-check-custom form-check-solid me-xxl-10 me-xl-10 me-lg-10 me-md-10 me-sm-10">
                                    <input class="form-check-input" type="radio" value="" name="Active">
                                    <label class="form-check-label">
                                        ทั้งหมด
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
               
            </div>

            <div class="card-footer text-center">
                <button type="submit" id="btnSearch" class="btn btn-primary btn-sm"><i class="fa fa-search"></i> ค้นหา</button>
                <button id="btnResetSearch" type="reset" class="btn btn-secondary btn-sm"><i class="fa fa-refresh"></i> ล้างเงื่อนไข</button>
            </div>
        }
    </div>
</div>

<div id="tbl"></div>
<div id="mdlDetail"></div>
<div id="mdlDetailSub"></div>


@section Scripts {
    <script>
        $("#btnSearch").click();
        $('#btnResetSearch').click(function () {
            setTimeout(
                function () {
                    $('#searchForm').submit();
                }, 500);
        });

        function showHideFilter() {
            var x = document.getElementById("divFilter");
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }

            var elem = document.getElementById("btnFilter");
            if (elem.value == "ซ่อน") elem.value = "แสดง";
            else elem.value = "ซ่อน";
        }        

    </script>

    <script>
        $(document).ready(function () {
            $("#_modalMasterAssetType").modal('show');
        });
    </script>
@* 
    @if (ViewBag.autoOpenAssetTypeId != null)
    {
        <script>
            $(document).ready(function () {
                alert('open');
            });
        </script>
    } *@
}

MOEN-ERP/Views/Master/MasterMaterial.cshtml
@section Title {
    <span class="fs-1 fw-semibold">วัสดุ</span>

}
@section Breadcrumb {
    <li class="breadcrumb-item pe-3"><a href="#" class="pe-3">หน้าแรก</a></li>
    <li class="breadcrumb-item pe-3 text-muted">วัสดุ</li>
}

<div class="card">

    <div class="card-header align-items-center py-5 gap-2 gap-md-5">
        <div class="card-title">
            <div class="d-flex align-items-center position-relative my-1">
                <h2>ค้นหา&nbsp;&nbsp;</h2>
                <input id="btnFilter" onclick="showHideFilter()" type="button" style="border:unset; font-size:x-small;" value="แสดง"></input><button style="border:unset; font-size:x-small;" onclick=" showHideFilter()"> <i class="fas fa-angle-down"></i></button>

            </div>
        </div>
        <div class="card-toolbar flex-row-fluid justify-content-end gap-5">
            <a class="btn btn-success btn-sm"
               data-ajax="true"
               data-ajax-method="POST"
               data-ajax-mode="replace"
               data-ajax-update="#mdlDetail"
               href='@Url.Action("MasterMaterialDetail", "Master")'>
                <i class="fa fa-plus"></i> สร้างใหม่
            </a>
        </div>
    </div>

    <div class="card-body" id="divFilter" style="display: none;">
        @using (Html.AjaxBeginForm("MasterMaterial", "Master", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "tbl" }, new { enctype = "multipart/form-data", id = "searchForm" }))
        {
            <div class="row mb-3">

                <div class="row col-md-6 mb-3">
                    <div class="col-4 text-end">
                        <label class="col-form-label">ชื่อวัสดุ</label>
                    </div>
                    <div class="col-8">
                        <input class="form-control form-control-sm" name="NameTh" />
                    </div>
                </div>
            </div>

            <div class="row mb-3">
                <div class="row col-md-6 mb-3">
                    <div class="col-4 text-end">
                        <label class="col-form-label">หมวดวัสดุ</label>
                    </div>
                    <div class="col-8 ">
                        <select class="form-select form-select-sm" name="GroupId" asp-items="ViewBag.MasterMaterialGroup">
                            <option value="">ทั้งหมด</option>
                        </select>
                    </div>
                </div>

                <div class="row col-md-6 mb-3 align-items-center">
                    <div class="col-4 text-end">
                        <label class="col-form-label">สถานะการใช้งาน</label>
                    </div>
                    <div class="col-8">
                        <div class="row fv-row">
                            <div class="d-xxl-flex d-xl-flex d-lg-flex d-md-flex d-sm-flex">
                                <div class="form-check form-check-custom form-check-solid me-xxl-10 me-xl-10 me-lg-10 me-md-10 me-sm-10">
                                    <input class="form-check-input" type="radio" value="true" name="Active" checked>
                                    <label class="form-check-label">
                                        ใช้งาน
                                    </label>
                                </div>
                                <div class="form-check form-check-custom form-check-solid me-xxl-10 me-xl-10 me-lg-10 me-md-10 me-sm-10">
                                    <input class="form-check-input" type="radio" value="false" name="Active">
                                    <label class="form-check-label">
                                        ไม่ใช้งาน
                                    </label>
                                </div>
                                <div class="form-check  form-check-custom form-check-solid me-xxl-10 me-xl-10 me-lg-10 me-md-10 me-sm-10">
                                    <input class="form-check-input" type="radio" value="" name="Active" >
                                    <label class="form-check-label">
                                        ทั้งหมด
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <div class="card-footer text-center">
                <button type="submit" id="btnSearch" class="btn btn-primary btn-sm"><i class="fa fa-search"></i> ค้นหา</button>
                <button id="btnResetSearch" type="reset" class="btn btn-secondary btn-sm"><i class="fa fa-refresh"></i> ล้างเงื่อนไข</button>
            </div>
        }
    </div>
</div>

<div id="tbl"></div>
<div id="mdlDetail"></div>

@section Scripts {
    <script>
        $("#btnSearch").click();
        $('#btnResetSearch').click(function () {
            setTimeout(
                function () {
                    $('#searchForm').submit();
                }, 500);
        });

        function showHideFilter() {
            var x = document.getElementById("divFilter");
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }

            var elem = document.getElementById("btnFilter");
            if (elem.value == "ซ่อน") elem.value = "แสดง";
            else elem.value = "ซ่อน";
        }

    </script>
}

MOEN-ERP/Views/Master/MasterMaterialGroup.cshtml
@section Title {
    <span class="fs-1 fw-semibold">หมวดพัสดุ</span>

}
@section Breadcrumb {
    <li class="breadcrumb-item pe-3"><a href="#" class="pe-3">หน้าแรก</a></li>
    <li class="breadcrumb-item pe-3 text-muted">หมวดพัสดุ</li>
}

<div class="card">

    <div class="card-header align-items-center py-5 gap-2 gap-md-5">
        <div class="card-title">
            <div class="d-flex align-items-center position-relative my-1">
                <h2>ค้นหา&nbsp;&nbsp;</h2>
                <input id="btnFilter" onclick="showHideFilter()" type="button" style="border:unset; font-size:x-small;" value="แสดง"></input><button style="border:unset; font-size:x-small;" onclick=" showHideFilter()"> <i class="fas fa-angle-down"></i></button>
            </div>
        </div>
        <div class="card-toolbar flex-row-fluid justify-content-end gap-5">
            <a class="btn btn-success btn-sm"
               data-ajax="true"
               data-ajax-method="POST"
               data-ajax-mode="replace"
               data-ajax-update="#mdlDetail"
               href='@Url.Action("MasterMaterialGroupDetail", "Master")'>
                <i class="fa fa-plus"></i> สร้างใหม่
            </a>
        </div>
    </div>

    <div class="card-body" id="divFilter" style="display: none;">
        @using (Html.AjaxBeginForm("MasterMaterialGroup", "Master", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "tbl" }, new { enctype = "multipart/form-data", id = "searchForm" }))
        {
            <div class="row mb-3">

                <div class="row col-md-6 mb-3">
                    <div class="col-4 text-end">
                        <label class="col-form-label">รหัสหมวดพัสดุ</label>
                    </div>
                    <div class="col-8">
                        <input class="form-control form-control-sm" name="Code" />
                    </div>
                </div>

                <div class="row col-md-6 mb-3">
                    <div class="col-4 text-end">
                        <label class="col-form-label">ชื่อหมวดพัสดุ</label>
                    </div>
                    <div class="col-8">
                        <input class="form-control form-control-sm" name="NameTh" />
                    </div>
                </div>

                <div class="row col-md-6 mb-3 align-items-center">
                    <div class="col-4 text-end">
                        <label class="col-form-label">สถานะการใช้งาน</label>
                    </div>
                    <div class="col-8">
                        <div class="row fv-row">
                            <div class="d-xxl-flex d-xl-flex d-lg-flex d-md-flex d-sm-flex">
                                <div class="form-check form-check-custom form-check-solid me-xxl-10 me-xl-10 me-lg-10 me-md-10 me-sm-10">
                                    <input class="form-check-input" type="radio" value="true" name="Active" checked>
                                    <label class="form-check-label">
                                        ใช้งาน
                                    </label>
                                </div>
                                <div class="form-check form-check-custom form-check-solid me-xxl-10 me-xl-10 me-lg-10 me-md-10 me-sm-10">
                                    <input class="form-check-input" type="radio" value="false" name="Active">
                                    <label class="form-check-label">
                                        ไม่ใช้งาน
                                    </label>
                                </div>
                                <div class="form-check  form-check-custom form-check-solid me-xxl-10 me-xl-10 me-lg-10 me-md-10 me-sm-10">
                                    <input class="form-check-input" type="radio" value="" name="Active">
                                    <label class="form-check-label">
                                        ทั้งหมด
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <div class="card-footer text-center">
                <button type="submit" id="btnSearch" class="btn btn-primary btn-sm"><i class="fa fa-search"></i> ค้นหา</button>
                <button id="btnResetSearch" type="reset" class="btn btn-secondary btn-sm"><i class="fa fa-refresh"></i> ล้างเงื่อนไข</button>
            </div>
        }
    </div>
</div>

<div id="tbl"></div>
<div id="mdlDetail"></div>

@section Scripts {
    <script>
        $("#btnSearch").click();
        $('#btnResetSearch').click(function () {
            setTimeout(
                function () {
                    $('#searchForm').submit();
                }, 500);
        });

        function showHideFilter() {
            var x = document.getElementById("divFilter");
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }

            var elem = document.getElementById("btnFilter");
            if (elem.value == "ซ่อน") elem.value = "แสดง";
            else elem.value = "ซ่อน";
        }
    </script>
}

MOEN-ERP/Views/Master/MasterOutputCode.cshtml
@section Title {
    <span class="fs-1 fw-semibold">ผลผลิต/โครงการ</span>

}
@section Breadcrumb {
    <li class="breadcrumb-item pe-3"><a href="#" class="pe-3">หน้าแรก</a></li>
    <li class="breadcrumb-item pe-3 text-muted">ผลผลิต/โครงการ</li>
}

<div class="card">

    <div class="card-header align-items-center py-5 gap-2 gap-md-5">
        <div class="card-title">
            <div class="d-flex align-items-center position-relative my-1">
                <h2>ค้นหา&nbsp;&nbsp;</h2>
                <input id="btnFilter" onclick="showHideFilter()" type="button" style="border:unset; font-size:x-small;" value="แสดง"></input><button style="border:unset; font-size:x-small;" onclick=" showHideFilter()"> <i class="fas fa-angle-down"></i></button>
            </div>
        </div>
        <div class="card-toolbar flex-row-fluid justify-content-end gap-5">
            <a class="btn btn-success btn-sm"
               data-ajax="true"
               data-ajax-method="POST"
               data-ajax-mode="replace"
               data-ajax-update="#mdlDetail"
               href='@Url.Action("MasterOutputCodeDetail", "Master")'>
                <i class="fa fa-plus"></i> สร้างใหม่
            </a>
        </div>
    </div>

    <div class="card-body" id="divFilter" style="display: none;">
        @using (Html.AjaxBeginForm("MasterOutputCode", "Master", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "tbl" }, new { enctype = "multipart/form-data", id = "searchForm" }))
        {
            <div class="row mb-3">
                <div class="row col-md-6 mb-3">
                    <div class="col-4 text-end">
                        <label class="col-form-label">ชื่อผลผลิต/โครงการ</label>
                    </div>
                    <div class="col-8 text-end">
                        <input class="form-control form-control-sm" name="Name" />
                    </div>
                </div>
                <div class="row col-md-6 mb-3">                   
                </div>

                <div class="row col-md-6 mb-3">
                    <div class="col-4 text-end">
                        <label class="col-form-label">ยุทธศาสตร์</label>
                    </div>
                    <div class="col-8">
                        <select class="form-select form-select-sm" name="StrategyCodeId" asp-items="ViewBag.MasterStrategyCode">
                            <option value="">ทั้งหมด</option>
                        </select>
                    </div>
                </div>

                <div class="row col-md-6 mb-3">
                    <div class="col-4 text-end">
                        <label class="col-form-label">แผนงาน</label>
                    </div>
                    <div class="col-8 text-end">
                        <select class="form-select form-select-sm" name="StrategicPlanCodeId" asp-items="ViewBag.MasterStrategicPlanCode">
                            <option value="">ทั้งหมด</option>
                        </select>
                    </div>
                </div>               

            </div>

            <div class="card-footer text-center">
                <button type="submit" id="btnSearch" class="btn btn-primary btn-sm"><i class="fa fa-search"></i> ค้นหา</button>
                <button id="btnResetSearch" type="reset" class="btn btn-secondary btn-sm"><i class="fa fa-refresh"></i> ล้างเงื่อนไข</button>
            </div>
        }
    </div>
</div>

<div id="tbl"></div>
<div id="mdlDetail"></div>

@section Scripts {
    <script>
        $("#btnSearch").click();
        $('#btnResetSearch').click(function () {
            setTimeout(
                function () {
                    $('#searchForm').submit();
                }, 500);
        });

        function showHideFilter() {
            var x = document.getElementById("divFilter");
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }

            var elem = document.getElementById("btnFilter");
            if (elem.value == "ซ่อน") elem.value = "แสดง";
            else elem.value = "ซ่อน";
        }

    </script>
}