MOEN-ERP/Controllers/BudgetController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Options;
using MOEN_ERP.Models.Common;
using MOEN_ERP.Models.Data;
using MOEN_ERP.Models.ViewModel;
using MOEN_ERP.Services;
using MOEN_ERP.Services.Repository;

namespace MOEN_ERP.Controllers
{
    public class BudgetController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly SettingsModel _settingsModels;
        private readonly IBudgetService _budgetService;
        private readonly IDropdowns _dropdowns;

        public BudgetController(HttpClient httpClient, IOptions<SettingsModel> option, IBudgetService budgetService, IDropdowns dropdowns)
        {
            _httpClient = httpClient;
            _settingsModels = option.Value;
            _budgetService = budgetService;
            _dropdowns = dropdowns;
        }
        public async Task<IActionResult> BudgetRequestList()
        {
            ViewBag.DropdownOrganization = await _dropdowns.DropdownOrganization();
            ViewBag.DropdownStatus = new SelectList(new[]
                {
                    new { Value = "1", Text = "Active" },
                    new { Value = "2", Text = "Inactive" }
                }, "Value", "Text");


            return View();
        }

        public async Task<IActionResult> SearchBudgetRequestList(BudgetRequestFilter filter)
        {
            // call budget service to get data
            List<BudgetRequestViewModel> data = _budgetService.GetBudgetListAsync(filter).Result;

            return PartialView("_partialView/_tableBudgetRequest", data);
        }

        public async Task<IActionResult> DeleteBudgetRequest(int Id)
        {
            // call budget service to get data
            _budgetService.DeleteBudgetRequest(Id);

            return Ok();
        }

        public async Task<IActionResult> BudgetRequestDetail(int? Id)
        {
            ViewBag.DropdownOrganization = await _dropdowns.DropdownOrganization();
            BudgetRequestDetailViewModel data = new BudgetRequestDetailViewModel();
            if (Id.HasValue)
            {
                data = _budgetService.GetBudgetRequestDetail(Id.Value).Result;
            }
            

            return View(data);
        }

        [HttpPost]
        public async Task<IActionResult> BudgetRequestDetail(BudgetRequestForm data)
        {
            ViewBag.DropdownOrganization = await _dropdowns.DropdownOrganization();
            
            BudgetRequestDetailViewModel result = _budgetService.SaveBudgetList(data).Result;


            return View(result);
        }

        public async Task<IActionResult> BudgetRequestExpensesDetail()
        {
            ViewBag.DropdownUnit = await _dropdowns.DropdownUnit();
            return View();
        }


        public IActionResult BudgetRequestSubsidyDetail()
        {
            return View();
        }
        public IActionResult BudgetRequestInvestmentDetail()
        {
            return View();
        }
        public IActionResult BudgetRequestOtherExpensesDetail()
        {
            return View();
        }

        /// <summary>
        /// จัดสรรงบเบิกจ่ายแทนกันกรมธุรกิจพลังงาน
        /// </summary>
        /// <returns></returns>
        public IActionResult BudgetAllocateDisbursementInsteadDetail()
        {
            return View();
        }
        /// <summary>
        /// รายการแผนการจัดซื้อจัดจ้าง
        /// </summary>
        /// <returns></returns>
        public IActionResult BudgetPlanProcurementList()
        {
            return View();
        }
        /// <summary>
        /// รายการเบิกจ่ายงบประมาณแผ่นดิน
        /// </summary>
        /// <returns></returns>
        public IActionResult BudgetRequisitionList()
        {
            return View();
        }
        /// <summary>
        /// รายละเอียดการเบิกจ่ายงบประมาณแผ่นดิน
        /// </summary>
        /// <returns></returns>
        public IActionResult BudgetRequisitionDetail()
        {
            return View();
        }
        /// <summary>
        /// รายการเบิกจ่ายงบประมาณเงินนอกงบประมาณ
        /// </summary>
        /// <returns></returns>
        public IActionResult BudgetRequisitionOutsideList()
        {
            return View();
        }
        /// <summary>
        /// รายละเอียดการเบิกจ่ายงบประมาณเงินนอกงบประมาณ
        /// </summary>
        /// <returns></returns>
        public IActionResult BudgetRequisitionOutsideDetail()
        {
            return View();
        }
        /// <summary>
        /// รายการจัดสรรเงินนอกงบประมาณ
        /// </summary>
        /// <returns></returns>
        public IActionResult BudgetAllocateOutsideList()
        {

            return View();
        }
        /// <summary>
        /// รายละเอียดการจัดสรรเงินนอกงบประมาณ
        /// </summary>
        /// <param name="BudgetType"></param>
        /// <returns></returns>
        public IActionResult BudgetAllocateOutsideDetail(int BudgetType)
        {
            ViewBag.BudgetType = BudgetType;
            return View();
        }

        /// รายการจัดสรรงบประมาณแผ่นดิน
        public IActionResult BudgetAllocateList()
        {
            return View();
        }
        /// รายละเอียดการจัดสรรงบประมาณแผ่นดิน
        public IActionResult BudgetAllocateDetail()
        {
            return View();
        }
        public IActionResult BudgetConsiderList()
        {
            return View();
        }
        public IActionResult BudgetConsiderDetail()
        {
            return View();
        }
        public IActionResult BudgetRequestOutsideList()
        {
            return View();
        }
        public IActionResult BudgetRequestOutsideDetail()
        {
            return View();
        }
        public IActionResult BudgetRequestProvinceList()
        {
            return View();
        }
        public IActionResult BudgetRequestProvinceDetail()
        {
            return View();
        }
        public IActionResult BudgetAllocateProvinceList()
        {
            return View();
        }
        public IActionResult BudgetAllocateProvinceDetail()
        {
            return View();
        }
        /// รายการจัดสรรงบเบิกจ่ายแทนกันกรมธุรกิจพลังงาน
        public IActionResult BudgetAllocateDisbursementInsteadList()
        {
            return View();
        }
        ///23. หน้าจอรายการแผนการใช้จ่ายงบประมาณ
        public IActionResult BudgetPlanExpenseList()
        {
            return View();
        }
        ///24. หน้าจอรายละเอียดแผนการใช้จ่ายงบประมาณ
        public IActionResult BudgetPlanExpenseDetail()
        {
            return View();
        }
        ///25.หน้าจอปรับแผนการใช้จ่ายงบประมาณ
        public IActionResult BudgetPlanExpenseAdjustList()
        {
            return View();
        }
        ///26.หน้าจอรายละเอียดปรับแผนการใช้จ่ายงบประมาณ
        public IActionResult BudgetPlanExpenseAdjustDetail()
        {
            return View();
        }
        ///27.หน้าจอรายการเงินเหลือจ่าย
        public IActionResult BudgetRemainList()
        {
            return View();
        }
        ///28.หน้าจอรายละเอียดเงินเหลือจ่าย
        public IActionResult BudgetRemainDetail()
        {
            return View();
        }
        ///29.หน้าจอรายการบริหารงบประมาณแผ่นดิน
        public IActionResult BudgetManagementList()
        {
            return View();
        }
        ///30.หน้าจอรายละเอียดการบริหารงบประมาณแผ่นดิน
        public IActionResult BudgetManagementDetail()
        {
            return View();
        }

        //31. หน้าจอรายการคำขอเงินงบประมาณเพิ่มเติม
        public IActionResult BudgetRequestMoreList()
        {
            return View();
        }
        //32. หน้าจอรายละเอียดคำขอเงินงบประมาณเพิ่มเติม
        public IActionResult BudgetRequestMoreDetail()
        {
            return View();
        }

        //33. หน้าจอรายการเบิกจ่ายงบจังหวัด/งบกลุ่มจังหวัด
        public IActionResult BudgetRequisitionProvinceList()
        {
            return View();
        }
        //34. หน้าจอรายละเอียดการเบิกจ่ายงบจังหวัด/งบกลุ่มจังหวัด
        public IActionResult BudgetRequisitionProvinceDetail()
        {
            return View();
        }

        //35. หน้าจอรายการเบิกจ่ายแทนกันกรมธุรกิจพลังงาน
        public IActionResult BudgetRequisitionDisbursementInsteadList()
        {
            return View();
        }
        //36. หน้าจอรายละเอียดการเบิกจ่ายแทนกันกรมธุรกิจพลังงาน
        public IActionResult BudgetRequisitionDisbursementInsteadDetail()
        {
            return View();
        }

        //37. หน้าจอรายการกันเหลื่อมปี
        public IActionResult BudgetOverlapYearList()
        {
            return View();
        }
        //38. หน้าจอรายละเอียดการกันเหลื่อมปี
        public IActionResult BudgetOverlapYearDetail()
        {
            return View();
        }

        //39. หน้าจอรายการทะเบียนคุมเงินนอกงบประมาณ
        public IActionResult BudgetManagementOutsideList()
        {
            return View();
        }
        //40. หน้าจอรายละเอียดทะเบียนคุมเงินนอกงบประมาณ
        public IActionResult BudgetManagementOutsideDetail()
        {
            return View();
        }
        //41. หน้าจอรายการทะเบียนคุมงบจังหวัด/งบกลุ่มจังหวัด
        public IActionResult BudgetManagementProvinceList()
        {
            return View();
        }
        //42. หน้าจอรายละเอียดทะเบียนคุมงบจังหวัด/งบกลุ่มจังหวัด
        public IActionResult BudgetManagementProvinceDetail()
        {
            return View();
        }
        //43. หน้าจอรายการทะเบียนคุมงบเบิกจ่ายแทนกันกรมธุรกิจพลังงาน
        public IActionResult BudgetManagementDisbursementInsteadList()
        {
            return View();
        }
        //44. หน้าจอรายละเอียดทะเบียนคุมงบเบิกจ่ายแทนกันกรมธุรกิจพลังงาน
        public IActionResult BudgetManagementDisbursementInsteadDetail()
        {
            return View();
        }
    }
}

MOEN-ERP/Views/Budget/BudgetAllocateDisbursementInsteadDetail.cshtml
@section Title {
    <span class="fs-1 fw-semibold">จัดสรรงบเบิกจ่ายแทนกันกรมธุรกิจพลังงาน</span>

}
@section Breadcrumb {
    <li class="breadcrumb-item pe-3"><a href="#" class="pe-3">หน้าแรก</a></li>
    <li class="breadcrumb-item pe-3 text-muted">จัดสรรงบเบิกจ่ายแทนกันกรมธุรกิจพลังงาน</li>
}

<div class="card">
    <div class="card-body">

        <div class="row mb-3">

            <div class="row col-xl-12 col-lg-12 col-md-12 mb-3">
                <div class="col-xxl col-xl-3 col-lg-3 col-md-3 col-sm-12">
                    <label class="col-form-label">ปีงบประมาณ</label>
                    <input type="text" class="form-control form-control-sm" disabled />
                </div>
                <div class="col-xxl col-xl-3 col-lg-3 col-md-3 col-sm-12">
                    <label class="col-form-label">สถานะ</label>
                    <input type="text" class="form-control form-control-sm" disabled />
                </div>
                <div class="col-xxl col-xl-3 col-lg-3 col-md-3 col-sm-12">
                    <label class="col-form-label">งบประมาณที่ได้รับอนุมัติ</label>
                    <input type="text" class="form-control form-control-sm text-end" value="244,500" />
                </div>
            </div>

            <div class="row col-xl-12 col-lg-12 col-md-12 mb-3">
                <div class="col-xxl col-xl-3 col-lg-3 col-md-3 col-sm-12 offset-8">
                    <label class="col-form-label">งบประมาณหลังปรับเกลี่ย</label>
                    <input type="text" class="form-control form-control-sm text-end" value="244,500" style="background-color:#C8FFCD" />
                </div>
            </div>

        </div>

        @* <div class="separator separator-dashed mt-5 mb-5"></div> *@

        <div class="row mb-3">
            <div class="table-responsive-xxl table-responsive-xl table-responsive-lg table-responsive-md table-responsive-sm">
                <table class="table table-row-dashed table-hover table-row-gray-300 align-middle gy-5 gs-7">
                    <thead class="table-primary">
                        <tr class="fw-semibold fs-6 text-gray-80 fw-bold">
                            <th class="text-center">ลำดับ</th>
                            <th class="text-center">จังหวัด</th>
                            <th class="text-center">งบประมาณจัดสรร</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="text-center">1</td>
                            <td class="text-center">อำนาจเจริญ</td>
                            <td class="text-center">
                                <input type="text" class="form-control form-control-sm text-center" value="3,142" />
                            </td>                           
                        </tr>
                         <tr>
                            <td class="text-center">2</td>
                            <td class="text-center">อุดรธานี</td>
                            <td class="text-center">
                                <input type="text" class="form-control form-control-sm text-center" value="3,457" />
                            </td>                           
                        </tr>
                        <tr>
                            <td class="text-center">3</td>
                            <td class="text-center">อุตรดิตถ์</td>
                            <td class="text-center">
                                <input type="text" class="form-control form-control-sm text-center" value="3,142" />
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center">4</td>
                            <td class="text-center">อุทัยธานี</td>
                            <td class="text-center">
                                <input type="text" class="form-control form-control-sm text-center" value="3,142" />
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>


    </div>
    <div class="card-footer">
        <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-save"></i> บันทึก</button>
        <button type="submit" class="btn btn-success btn-sm"><i class="fa fa-check"></i> ยืนยัน</button>    
        <a href="@Url.Action("BudgetAllocateDisbursementInsteadList","Budget")" class="btn btn-secondary btn-sm"><i class="fa fa-refresh"></i> กลับหน้าหลัก</a>
        <button type="submit" class="btn btn-info btn-sm"><i class="fa fa-print"></i> พิมพ์</button>
    </div>
</div>

MOEN-ERP/Views/Budget/BudgetAllocateOutsideList.cshtml
@section Title {
    <span class="fs-1 fw-semibold">รายการจัดสรรเงินนอกงบประมาณ</span>

}
@section Breadcrumb {
    <li class="breadcrumb-item pe-3"><a href="#" class="pe-3">หน้าแรก</a></li>
    <li class="breadcrumb-item pe-3 text-muted">รายการจัดสรรเงินนอกงบประมาณ</li>
}

<div class="card">
    <div class="card-header align-items-center py-5 gap-2 gap-md-5">
        <div class="card-title">
            <div class="d-flex align-items-center position-relative my-1">
                <h2>ค้นหา</h2>
            </div>
        </div>
        <div class="card-toolbar flex-row-fluid justify-content-end gap-5">
        </div>
    </div>
    <div class="card-body">

        <div class="row mb-3">

            <div class="row col-md-6 mb-3">
                <div class="col-4 text-end">
                    <label class="col-form-label">ปีงบประมาณ</label>
                </div>
                <div class="col-8">
                    <input class="form-control form-control-sm" />
                </div>
            </div>

            <div class="row col-md-6 mb-3">
                <div class="col-4 text-end">
                    <label class="col-form-label">ชื่อโครงการ</label>
                </div>
                <div class="col-8">
                    <input class="form-control form-control-sm" />
                </div>
            </div>

          
        </div>

        <div class="row mb-3">
            <div class="row col-md-6 mb-3">
                <div class="col-4 text-end">
                    <label class="col-form-label">หน่วยงาน</label>
                </div>
                <div class="col-8">
                    <select class="form-select form-select-sm">
                        <option value="">ทั้งหมด</option>
                    </select>
                </div>
            </div>
            <div class="row col-md-6 mb-3">
                <div class="col-4 text-end">
                    <label class="col-form-label">สถานะ</label>
                </div>
                <div class="col-8">
                    <select class="form-select form-select-sm">
                        <option value="">ทั้งหมด</option>
                    </select>
                </div>
            </div>
        </div>


    </div>
    <div class="card-footer text-center">
        <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-search"></i> ค้นหา</button>
        <button id="btnResetSearch" type="reset" class="btn btn-secondary btn-sm"><i class="fa fa-refresh"></i> ล้างเงื่อนไข</button>
    </div>
</div>


<div class="card mt-10">
    <div class="card-body">
        <div class="table-responsive-xxl table-responsive-xl table-responsive-lg table-responsive-md table-responsive-sm">
            <table id="table1" class="table table-row-dashed table-hover table-row-gray-300 align-middle gy-5 gs-7 ">
                <thead class="table-primary">
                    <tr class="fw-semibold fs-6 text-gray-80 fw-bold">
                        <th class="text-center" style="width:10%"></th>
                        <th class="text-center" style="width:5%">#</th>
                        <th class="text-center">ปีงบประมาณ</th>
                        <th class="text-center">หน่วยงาน</th>
                        <th class="text-center">ชื่อโครงการ</th>
                        <th class="text-center">งบประมาณ</th>
                        <th class="text-center">กองทุน</th>
                        <th class="text-center">สถานะ</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="text-center">
                            <a href="@Url.Action("BudgetAllocateOutsideDetail","Budget",new{ BudgetType = 1 })" class="btn btn-icon btn-sm btn-light-warning text-gray-800 text-hover-white fw-bold mb-0"
                               data-bs-toggle="tooltip" data-bs-custom-class="tooltip-inverse" title="แก้ไขรายละเอียด">
                                <i class="fa fa-edit fs-4"></i>
                            </a>
                        </td>
                        <td class="text-center">1</td>
                        <td class="text-center">2567</td>
                        <td class="text-center">สพจ.ระยอง</td>
                        <td class="text-center">โครงการลดการใช้พลังงานในภาครัฐ</td>
                        <td class="text-center">271,208.85</td>
                        <td class="text-center">กองทุนอนุรักษ์</td>
                        <td class="text-center"></td>
                    </tr>
                     <tr>
                        <td class="text-center">
                            <a href="@Url.Action("BudgetAllocateOutsideDetail","Budget",new{ BudgetType = 2 })" class="btn btn-icon btn-sm btn-light-warning text-gray-800 text-hover-white fw-bold mb-0"
                               data-bs-toggle="tooltip" data-bs-custom-class="tooltip-inverse" title="แก้ไขรายละเอียด">
                                <i class="fa fa-edit fs-4"></i>
                            </a>
                        </td>
                        <td class="text-center">2</td>
                        <td class="text-center">2567</td>
                        <td class="text-center">ส่วนกลาง</td>
                        <td class="text-center">โครงการพัฒนาบุคลากรตาม Training Roadmap</td>
                        <td class="text-center">4,692,400</td>
                        <td class="text-center">กองทุนสัมปทาน</td>
                        <td class="text-center"></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $('#table1').DataTable({
            language: {
                url: `${baseURL}/js/th.json`,
            },
            "paging": true,
            "searching": false,
            "lengthChange": true,
            "ordering": false,
            "info": true,
            "autoWidth": false,
            "columnDefs": [
                { "orderable": false, "targets": 0 }
            ],

            "responsive": true,
            responsive: {
                details: {
                    display: $.fn.dataTable.Responsive.display.childRowImmediate,
                    type: 'none',
                    target: ''
                }
            },
            "pageLength": 10,
            deferLoading: 10,
            dom: '<"float-left"f>rt<"row"<"col-sm-4"i><"col-sm-4 text-center"l><"col-sm-4"p>>'
        });
    </script>
}

MOEN-ERP/Views/Budget/BudgetAllocateProvinceList.cshtml
@section Title {
    <span class="fs-1 fw-semibold">รายการจัดสรรงบจังหวัด/งบกลุ่มจังหวัด</span>

}
@section Breadcrumb {
    <li class="breadcrumb-item pe-3"><a href="#" class="pe-3">หน้าแรก</a></li>
    <li class="breadcrumb-item pe-3 text-muted">รายการจัดสรรงบจังหวัด/งบกลุ่มจังหวัด</li>
}

<div class="card">

    <div class="card-header align-items-center py-5 gap-2 gap-md-5">
        <div class="card-title">
            <div class="d-flex align-items-center position-relative my-1">
                <h2>ค้นหา</h2>
            </div>
        </div>
   
    </div>

    <div class="card-body">

        <div class="row mb-3">

            <div class="row col-md-6 mb-3">
                <div class="col-4 text-end">
                    <label class="col-form-label">ปีงบประมาณ</label>
                </div>
                <div class="col-8">
                    <input class="form-control form-control-sm" />
                </div>
            </div>

            <div class="row col-md-6 mb-3">
                <div class="col-4 text-end">
                    <label class="col-form-label">ชื่อโครงการ</label>
                </div>
                <div class="col-8">
                    <input class="form-control form-control-sm" />
                </div>
            </div>

            <div class="row col-md-6 mb-3">
                <div class="col-4 text-end">
                    <label class="col-form-label">หน่วยงาน</label>
                </div>
                <div class="col-8">
                    <select class="form-select form-select-sm">
                        <option value="">ทั้งหมด</option>
                    </select>
                </div>
            </div>

            <div class="row col-md-6 mb-3">
                <div class="col-4 text-end">
                    <label class="col-form-label">สถานะ</label>
                </div>
                <div class="col-8">
                    <select class="form-select form-select-sm">
                        <option value="">ทั้งหมด</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="card-footer text-center">
            <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-search"></i> ค้นหา</button>
            <button id="btnResetSearch" type="reset" class="btn btn-secondary btn-sm"><i class="fa fa-refresh"></i> ล้างเงื่อนไข</button>
        </div>
    </div>
</div>

<div class="card mt-10">
    <div class="card-body">
        <div class="table-responsive-xxl table-responsive-xl table-responsive-lg table-responsive-md table-responsive-sm">
            <table id="table1" class="table table-row-dashed table-hover table-row-gray-300 align-middle gy-5 gs-7 ">
                <thead class="table-primary">
                    <tr class="fw-semibold fs-6 text-gray-80 fw-bold">
                        <th class="text-center"></th>
                        <th class="text-center" style="width:5%">#</th>
                        <th class="text-center">ปีงบประมาณ</th>
                        <th class="text-center">หน่วยงาน</th>
                        <th class="text-center">ชื่อโครงการ</th>
                        <th class="text-center">งบประมาณ</th>
                        <th class="text-center">สถานะ</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="text-center">
                            <a href="@Url.Action("BudgetAllocateProvinceDetail","Budget")" class="btn btn-icon btn-sm btn-light-warning text-gray-800 text-hover-white fw-bold mb-0"
                               data-bs-toggle="tooltip" data-bs-custom-class="tooltip-inverse" title="แก้ไขรายละเอียด">
                                <i class="fa fa-edit fs-4"></i>
                            </a>
                            <a href="#" class="btn btn-icon btn-sm btn-light-danger text-gray-800 text-hover-white fw-bold mb-0"
                               data-bs-toggle="tooltip" data-bs-custom-class="tooltip-inverse" title="ลบ">
                                <i class="fa fa-trash fs-4"></i>
                            </a>
                        </td>
                        <td class="text-center">1</td>
                        <td class="text-center">2567</td>
                        <td class="text-center">สพจ.สิงห์บุรี</td>
                        <td class="text-center">โครงการพัฒนาแหล่งท่องเที่ยวรองรับการท่องเที่ยวมูลค่าสูง</td>
                        <td class="text-center">5,803,000</td>
                        <td class="text-center">ส่งเรื่อง</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $('#tbl1').DataTable({
            language: {
                url: `${baseURL}/js/th.json`,
            },
            "paging": true,
            "searching": false,
            "lengthChange": true,
            "ordering": false,
            "info": true,
            "autoWidth": false,
            "columnDefs": [
                { "orderable": false, "targets": 0 }
            ],

            "responsive": true,
            responsive: {
                details: {
                    display: $.fn.dataTable.Responsive.display.childRowImmediate,
                    type: 'none',
                    target: ''
                }
            },
            "pageLength": 10,
            deferLoading: 10,
            dom: '<"float-left"f>rt<"row"<"col-sm-4"i><"col-sm-4 text-center"l><"col-sm-4"p>>'
        });
    </script>
}

MOEN-ERP/Views/Budget/BudgetOverlapYearList.cshtml
@section Title {
    <span class="fs-1 fw-semibold">กันเหลื่อมปี</span>

}
@section Breadcrumb {
    <li class="breadcrumb-item pe-3"><a href="#" class="pe-3">หน้าแรก</a></li>
    <li class="breadcrumb-item pe-3 text-muted">กันเหลื่อมปี</li>
}

<div class="card">

    <div class="card-header align-items-center py-5 gap-2 gap-md-5">
        <div class="card-title">
            <div class="d-flex align-items-center position-relative my-1">
                <h2>ค้นหา</h2>
            </div>
        </div>
        <div class="card-toolbar flex-row-fluid justify-content-end gap-5">
            <a id="btnAdd" class="btn btn-success btn-sm" href="@Url.Action("BudgetOverlapYearDetail","Budget")">
                <i class="fa fa-plus"></i> สร้างใหม่
            </a>
        </div>
    </div>

    <div class="card-body">
        <div class="row mb-3">
            <div class="row col-md-6 mb-3">
                <div class="col-4 text-end">
                    <label class="col-form-label">ปีงบประมาณ</label>
                </div>
                <div class="col-8">
                    <input class="form-control form-control-sm" />
                </div>
            </div>
        </div>
        <div class="card-footer text-center">
            <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-search"></i> ค้นหา</button>
            <button id="btnResetSearch" type="reset" class="btn btn-secondary btn-sm"><i class="fa fa-refresh"></i> ล้างเงื่อนไข</button>
        </div>
    </div>
</div>

<div class="card mt-10">
    <div class="card-body">
        <div class="table-responsive-xxl table-responsive-xl table-responsive-lg table-responsive-md table-responsive-sm">
            <table id="table1" class="table table-row-dashed table-hover table-row-gray-300 align-middle gy-5 gs-7 ">
                <thead class="table-primary">
                    <tr class="fw-semibold fs-6 text-gray-80 fw-bold">
                        <th class="text-center" width="100"></th>
                        <th class="text-center" style="width:5%">#</th>
                        <th class="text-center">ปีงบประมาณ</th>
                        <th class="text-center">งบประมาณ</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="text-center">
                            <a href="@Url.Action("BudgetOverlapYearDetail","Budget")" class="btn btn-icon btn-sm btn-light-warning text-gray-800 text-hover-white fw-bold mb-0"
                               data-bs-toggle="tooltip" data-bs-custom-class="tooltip-inverse" title="แก้ไขรายละเอียด">
                                <i class="fa fa-edit fs-4"></i>
                            </a>
                        </td>
                        <td class="text-center">1</td>
                        <td class="text-center">2567</td>
                        <td class="text-center">โครงการลดการใช้พลังงานในภาครัฐ</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $('#tbl1').DataTable({
            language: {
                url: `${baseURL}/js/th.json`,
            },
            "paging": true,
            "searching": false,
            "lengthChange": true,
            "ordering": false,
            "info": true,
            "autoWidth": false,
            "columnDefs": [
                { "orderable": false, "targets": 0 }
            ],

            "responsive": true,
            responsive: {
                details: {
                    display: $.fn.dataTable.Responsive.display.childRowImmediate,
                    type: 'none',
                    target: ''
                }
            },
            "pageLength": 10,
            deferLoading: 10,
            dom: '<"float-left"f>rt<"row"<"col-sm-4"i><"col-sm-4 text-center"l><"col-sm-4"p>>'
        });
    </script>
}