MOEN-ERP/Controllers/AttachFileController.cs
using MOEN_ERP.Models.Common;
using MOEN_ERP.Models.Data;
using MOEN_ERP.Models.ViewModel;
using MOEN_ERP.Services.Repository;
using Microsoft.AspNetCore.Mvc;
//using Microsoft.Extensions.FileProviders;
using Newtonsoft.Json;
using System;
using System.IO;
using MOEN_ERP.DAL.Models;

namespace MOEN_ERP.Controllers
{
    public class AttachFileController : Controller
    {
        //private readonly IDataService _dataService;
        private readonly IAttachFileService _attachFile;
        public AttachFileController(IAttachFileService attachFile)
        {
            _attachFile = attachFile;
        }

        #region Attach File
        [HttpPost]
        public async Task<ActionResult> RenderAttachFileImage(string eleId, int refId, string refGuidId, string fileGuidId, string refTable, string refCmp, bool? read)
        {
            var attImgList = new AssetImage();
            if (refId > 0)
            {
                var att = await _attachFile.GetAttachFileListImageAsync(new AssetImage()
                {
                    AssetId = refId,
                    ReferenceGroup = refCmp
                });
                if (att.Count() > 0) attImgList = att.FirstOrDefault();
            }
            else if (fileGuidId != null)
            {
                string[] arrFileGuid = fileGuidId.Split("||");
                foreach (var rFile in arrFileGuid)
                {
                    if (!string.IsNullOrEmpty(rFile))
                    {
                        var att = await _attachFile.GetAttachFileImageGuidNoDataAsync(rFile);
                        attImgList = att;
                    }
                }
            }


            TempData["eleId"] = eleId;
            TempData["refId"] = refId;
            TempData["refGuidId"] = refGuidId;
            TempData["fileGuidId"] = fileGuidId;
            TempData["refTable"] = refTable;
            TempData["refCmp"] = refCmp;
            TempData["readOnly"] = read;
            return PartialView("_RenderAttachFileImage", attImgList);
        }
        #endregion

        #region Attach File PDF List
        [HttpPost]
        public async Task<ActionResult> RenderAttachFilePDFList(string eleId, int refId, string refGuidId, string fileGuidId, string refTable, string refCmp, bool? read)
        {
            var attImgList = new List<AttachFile>();
            if (refId > 0)
            {
                var att = await _attachFile.GetAttachFileNoDataListAsync(new AttachFile()
                {
                    ReferenceId = refId,
                    ReferenceTable = refTable,
                    ReferenceGroup = refCmp
                });
                attImgList.AddRange(att);
            }
            else
            {
                if (fileGuidId != null)
                {
                    string[] arrFileGuid = fileGuidId.Split("||");
                    foreach (var rFile in arrFileGuid)
                    {
                        if (!string.IsNullOrEmpty(rFile))
                        {
                            var att = await _attachFile.GetAttachFileGuidNoDataAsync(rFile);

                            if (att != null) attImgList.Add(att);
                        }
                    }
                }
            }

            TempData["eleId"] = eleId;
            TempData["refId"] = refId;
            TempData["refGuidId"] = refGuidId;
            TempData["fileGuidId"] = fileGuidId;
            TempData["refTable"] = refTable;
            TempData["refCmp"] = refCmp;
            TempData["readOnly"] = read;
            return PartialView("_RenderAttachFilePDFList", attImgList);
        }

        [HttpPost]
        public async Task<ActionResult> AddItemFilePDF(string[] fileGuidId, string[] imageName, int refId, string refGuidId, string refCmp, string refTable, string eleId, string read)
        {
            //AttachFileViewModel attImg = new AttachFileViewModel();
            var attImgList = new List<AttachFile>();

            var count = 0;
            if (imageName != null && imageName.Length > 0) count = imageName.Count();

            var i = 0;
            if (fileGuidId != null)
            {
                foreach (var itm in fileGuidId)
                {
                    var guid = Guid.Parse(itm);
                    //var att = await _attachFile.GetAttachFileGuidAsync(guid.ToString());
                    var att = await _attachFile.GetAttachFileGuidNoDataAsync(guid.ToString());
                    att.Filename = imageName[i];
                    attImgList.Add(att);
                    i++;
                }
            }
            TempData["eleId"] = eleId;
            TempData["refId"] = refId;
            TempData["refGuidId"] = refGuidId;
            TempData["refTable"] = refTable;
            TempData["refCmp"] = refCmp;
            TempData["readOnly"] = read;
            TempData["fileGuidId"] = string.Join("||", fileGuidId);
            attImgList.Add(new AttachFile());
            if (count != 0 && count == attImgList.Count()) ViewBag.errorAddImg = "กรุณาใส่รูปให้ครบก่อนเพิ่มรูปภาพ";
            return PartialView("_RenderAttachFilePDFList", attImgList);
        }

        #endregion


        #region Attach File List
        [HttpPost]
        public async Task<ActionResult> RenderAttachFileList(string eleId, int refId, string refGuidId, string fileGuidId, string refTable, string refCmp, bool? read, bool? list)
        {
            var attImgList = new List<AttachFile>();
            if (refId > 0)
            {
                var att = await _attachFile.GetAttachFileNoDataListAsync(new AttachFile()
                {
                    ReferenceId = refId,
                    ReferenceTable = refTable,
                    ReferenceGroup = refCmp
                });
                attImgList.AddRange(att);
            }
            else
            {
                if (fileGuidId != null)
                {
                    string[] arrFileGuid = fileGuidId.Split("||");
                    foreach (var rFile in arrFileGuid)
                    {
                        if (!string.IsNullOrEmpty(rFile))
                        {
                            var att = await _attachFile.GetAttachFileGuidNoDataAsync(rFile);

                            if (att != null) attImgList.Add(att);
                        }
                    }
                }
            }

            TempData["eleId"] = eleId;
            TempData["refId"] = refId;
            TempData["refGuidId"] = refGuidId;
            TempData["fileGuidId"] = fileGuidId;
            TempData["refTable"] = refTable;
            TempData["refCmp"] = refCmp;
            TempData["readOnly"] = read;
            TempData["list"] = list;

            return PartialView("_RenderAttachFileList", attImgList);
        }

        [HttpPost]
        [DisableRequestSizeLimit]
        public async Task<IActionResult> UplaodFile()
        {
            try
            {
                var user = new Appz(HttpContext).CurrentSignInUser;

                var files = Request.Form.Files[0];

                var refCmp = Request.Form["refCmp"].ToString();
                var refId = !string.IsNullOrEmpty(Request.Form["refId"].ToString()) ? Convert.ToInt32(Request.Form["refId"].ToString()) : 0;
                var refTable = Request.Form["refTable"].ToString();

                if (files == null || files.Length == 0)
                    return Content("file not selected");

                byte[] fileByte;
                using (var stream = new MemoryStream())
                {
                    files.CopyTo(stream);
                    fileByte = stream.ToArray();
                }

                if (files == null || files.Length == 0) return Json(new { status = "failed", remark = "file not selected" });


                var fileUpload = new AttachFile()
                {
                    CreateOn = DateTime.Now,
                    CreateBy = user.User.Id,
                    RowGuid = Guid.NewGuid(),
                    ReferenceTable = refTable,
                    ReferenceId = refId,
                    ReferenceGroup = refCmp,
                    FileSize = files.Length,
                    Filename = files.FileName,
                    Extension = files.ContentType,
                    FileData = fileByte,
                };
                var res = await _attachFile.AddAttachFileAsync(fileUpload);
                if (res.Type == "success")
                {
                    var resData = JsonConvert.DeserializeObject<AttachFile>(res.Data.ToString());
                    fileUpload.FileData = null;
                    return Json(new { Success = true, attach = fileUpload });

                }
                else
                {
                    return Json(new { Success = false, Remark = res.Message });

                }
            }
            catch (Exception ex)
            {

                return Json(new { Success = false, attach = (AttachFile)null, Remark = ex.Message });
            }


        }

        [HttpPost]
        [DisableRequestSizeLimit]
        public async Task<IActionResult> UplaodFileImage()
        {
            try
            {
                var user = new Appz(HttpContext).CurrentSignInUser;

                var files = Request.Form.Files[0];

                var refCmp = Request.Form["refCmp"].ToString();
                var refId = !string.IsNullOrEmpty(Request.Form["refId"].ToString()) ? Convert.ToInt32(Request.Form["refId"].ToString()) : 0;
                var refTable = Request.Form["refTable"].ToString();

                if (files == null || files.Length == 0)
                    return Content("file not selected");

                byte[] fileByte;
                using (var stream = new MemoryStream())
                {
                    files.CopyTo(stream);
                    fileByte = stream.ToArray();
                }

MOEN-ERP/Views/AttachFile/_RenderAttachFile.cshtml
@using MOEN_ERP.Services;
@using MOEN_ERP.Utilities;
@model List<MOEN_ERP.DAL.Models.AttachFile>


<style>


    .articles a {
        text-decoration: none !important;
        display: block;
        margin-bottom: 0;
        color: #555
    }

    .articles .badge {
        font-size: 0.7em;
        padding: 5px 10px;
        line-height: 1;
        margin-left: 10px
    }

    .articles .item {
        padding: 6px;
        margin: 4px;
        border: 1px dashed #009ef7;
        background-color: #f1faff;
        border-radius: 0.475rem !important;
    }

        .articles .item:nth-of-type(even) {
            background: #fafafa
        }

        .articles .item .image {
            min-width: 50px;
            max-width: 50px;
            height: 50px;
            margin-right: 15px
        }

        .articles .item img {
            padding: 3px;
            border: 1px solid #28a745
        }
        /*
                                    .articles .item i {
                                        padding: 3px;
                                        border: 1px solid #28a745;
                                        font-size: 36px;
                                    }*/

        .articles .item h3 {
            color: #555;
            font-weight: 400;
            margin-bottom: 0
        }

        .articles .item small {
            color: #aaa;
            font-size: 0.75em
        }

</style>

@{
    var baseURL = MyHttpContext.AppBaseUrl;
    var eleId = TempData["eleId"];
    var read = Convert.ToBoolean(TempData["readOnly"]);
    var refGuidId = TempData["refGuidId"];
    var fileGuidId = TempData["fileGuidId"];
    int i = 1;
}
<div class="container">
    <div class="row">

        <div class="col-lg-12">
            <div class="articles card">

                <div class="card-body" style="padding:0">
                    @{
                        var idImg = $"desimg{eleId}" + i;
                        var inputId = $"txtNameimg{eleId}" + i;

                    }


                    @foreach (var item in Model)
                    {
                        var pic = item?.RowGuid != null ? item?.Filename : "ไฟล์ที่ " + i;
                        var imgIcon = baseURL + "/images/files/file.png";
                        @switch (item.Extension)
                        {
                            case "image/jpeg":
                                imgIcon = baseURL + "/images/files/jpg.png";
                                break;
                            case "image/png":
                                imgIcon = baseURL + "/images/files/png.png";
                                break;
                            case "application/pdf":
                                imgIcon = baseURL + "/images/files/pdf.png";
                                break;
                        }


                        if (item?.RowGuid != null)
                        {
                            <div class="item d-flex" id="@idImg">
                                <input type="hidden" name="@refGuidId" value="@item.RowGuid" />
                                <input type="hidden" name="imageName" id="@inputId" value="@item.Filename" />
                                <div class="image">
                                    <img src="@imgIcon" alt="..." class="img-fluid rounded-circle">
                                </div>
                                <div class="text">
                                    <a href="javascript:void;" onclick="window.open('@Url.Action("ViewAttachFile", "AttachFile", new { @id = item.RowGuid, refTable=item.ReferenceTable, refCmp=item.ReferenceGroup })', '_blank');">
                                        <h3 class="h5">@item.Filename</h3>
                                    </a>
                                    <small>File size: @FileSizeSuffix.SizeSuffix(item.FileSize ?? 0)</small>
                                </div>
                                <div class="ms-auto p-4">
                                    <a href="javascript:void;" onclick="Swal.fire({title: 'ต้องการลบไฟล์ ใช่หรือไม่?',icon: 'info',showDenyButton: true,confirmButtonText: 'ตกลง',denyButtonText: `ยกเลิก`,}).then((result) => {if (result.isConfirmed) {showWait();deleteImage('@idImg','@item.RowGuid');}});">
                                        <i class="fa fa-trash text-danger"></i>
                                    </a>
                                </div>
                            </div>
                        }

                        i++;
                    }


                    @if (read == null || read == false)
                    {
                        idImg = $"desimg{eleId}" + i + 1;
                        <!--begin::Input group-->
                        <div class="fv-row" id="@idImg">
                            <!--begin::Dropzone-->
                            <div class="dropzone needsclick" id="kt_dropzonejs_example_1">
                                <!--begin::Message-->
                                <div class="dz-message ">
                                    <i class="ki-duotone ki-file-up fs-3x text-primary"><span class="path1"></span><span class="path2"></span></i>

                                    <!--begin::Info-->
                                    <div class="ms-4">
                                        <h3 class="fs-5 fw-bold text-gray-900 mb-1">วางไฟล์ที่นี่หรือคลิกเพื่ออัปโหลด</h3>
                                        <span class="fs-7 fw-semibold text-gray-400">รองรับไฟล์ ขนาดไม่เกิน 30 MB</span>
                                    </div>
                                    <!--end::Info-->
                                </div>
                            </div>
                            <!--end::Dropzone-->
                        </div>
                        <!--end::Input group-->
                        <script>
                            initFileDropArea('@idImg', '@eleId', '@TempData["refId"]', '@TempData["refGuidId"]', '@TempData["fileGuidId"]', '@TempData["refTable"]', '@TempData["refCmp"]', '@read');

                        </script>
                    }


                </div>
            </div>
        </div>


    </div>
</div>


<script>
    var refId = @TempData["refId"];
    var refGuidId = '@TempData["refGuidId"]';
    var refTable = '@TempData["refTable"]';
    var refCmp = '@TempData["refCmp"]';
    var read = '@TempData["readOnly"]';

    function addImgInDiv(res) {

        //console.log(res.id);

        var arrImgId = $('input[name="@refGuidId"]').map(function () {
            return this.value;
        }).get();
        var arrImgNameId = $('input[name="imageName"]').map(function () {
            return this.value;
        }).get();

        $.ajax({
            url: "@Url.Action("AddItemFile", "AttachFile")",
            data: {
                fileGuidId: arrImgId,
                imageName: arrImgNameId, refId: refId, refGuidId: refGuidId, refTable: refTable, refCmp: refCmp, eleId: res.id, read: read
            },
            type: "Post",
            success: function (result) {
                $("#" + res.id).empty();
                $("#" + res.id).html(result);
            }
        });

    }

    @if (ViewBag.errorAddImg != null)
    {
        <text>
            Swal.fire({
                title: "@ViewBag.errorAddImg",
                icon: "error",
                buttons: "ปิด",
            });
        </text>
    }

</script>

MOEN-ERP/Views/AttachFile/_RenderAttachFileImage.cshtml
@model MOEN_ERP.DAL.Models.AssetImage

@{
    var eleId = TempData["eleId"];
    var refId = TempData["refId"];
    var refGuidId = TempData["refGuidId"];
    var fileGuidId = TempData["fileGuidId"];
    var refTable = TempData["refTable"];
    var refCmp = TempData["refCmp"];
    var read = Convert.ToBoolean(TempData["readOnly"]);

    int i = 1;
    var idImg = $"desimg{eleId}" + i;
    var inputId = $"txtNameimg{eleId}" + i;
    var pic = "";
}

<style>

    .dropzone {
        width: 100%;
        height: 400px;
        cursor: pointer;
        display: flex;
            flex-direction: column;
        justify-content: center;
        align-items: center;
        
    }

</style>


@if (Model?.Id != 0)
{
    <div class="row" id="@idImg">
        <div class="dropzone img-wrapper">
            <div class="imgplace p-5 @(Model?.RowGuid != null ? "showimg":"") ">
                <input type="hidden" name="@refGuidId" value="@Model.RowGuid" id="@(refGuidId?.ToString() + refCmp?.ToString())" />
                <img src="@Url.Action("ViewAttachFileImage", "AttachFile", new { @id = Model.RowGuid, refCmp=Model.ReferenceGroup })" class="pointer" onclick="window.open('@Url.Action("ViewAttachFileImage", "AttachFile", new { @id = Model.RowGuid, refCmp=Model.ReferenceGroup })', '_blank');" />
                @if (read == null || read == false)
                {
                    <a href="javascript:;" class="img-delete" onclick="Swal.fire({title: 'ต้องการลบไฟล์ ใช่หรือไม่?',icon: 'info',showDenyButton: true,confirmButtonText: 'ตกลง',denyButtonText: `ยกเลิก`,}).then((result) => {if (result.isConfirmed) {showWait();deleteImage('@Model.RowGuid','@eleId', '@refId', '@refGuidId', '', '@refTable', '@refCmp', '@read');}});"><i class="fa fa-trash text-danger"></i></a>
                }

            </div>
        </div>
    </div>

}
else
{
    idImg = $"desimg{eleId}" + i + 1;
    <div class="row" id="@idImg">
        <div class="dropzone needsclick">
            <div class="dz-message ">
                <input type="hidden" name="@refGuidId" id="@(refGuidId?.ToString() + refCmp?.ToString())" />
                <i class="ki-duotone ki-file-up fs-3x text-primary"><span class="path1"></span><span class="path2"></span></i>
                <div class="ms-4 mt-5">
                    <h3 class="fs-5 fw-bold text-gray-900 mb-1 ">วางรูปที่นี่หรือคลิกเพื่ออัปโหลด</h3>
                </div>
            </div>
        </div>
    </div>

    <script>
        initFileImageDropArea('@idImg', '@eleId', '@TempData["refId"]', '@TempData["refGuidId"]', '@TempData["fileGuidId"]', '@TempData["refTable"]', '@TempData["refCmp"]', '@read');

    </script>
}


<script>
    var refId = @TempData["refId"];
    var refGuidId = '@TempData["refGuidId"]';
    var refTable = '@TempData["refTable"]';
    var refCmp = '@TempData["refCmp"]';
    var read = '@TempData["readOnly"]';

    function addImgInDiv(res) {

        //console.log(res.id);

        var arrImgId = $('input[name="@refGuidId"]').map(function () {
            return this.value;
        }).get();
        var arrImgNameId = $('input[name="imageName"]').map(function () {
            return this.value;
        }).get();

        $.ajax({
            url: "@Url.Action("AddItemImage", "AttachFile")",
            data: {
                fileGuidId: arrImgId,
                imageName: arrImgNameId, refId: refId, refGuidId: refGuidId, refTable: refTable, refCmp: refCmp, eleId: res.id, read: read
            },
            type: "Post",
            success: function (result) {
                $("#" + res.id).empty();
                $("#" + res.id).html(result);
            }
        });

    }

    @if (ViewBag.errorAddImg != null)
    {
        <text>
            Swal.fire({
                title: "@ViewBag.errorAddImg",
                icon: "error",
                buttons: "ปิด",
            });
        </text>
    }

</script>

MOEN-ERP/Views/AttachFile/_RenderAttachFileImageList.cshtml
@model List<MOEN_ERP.DAL.Models.AttachFile>

@{
    int i = 1;
}

<style>
    .pointer {
        cursor: pointer;
    }
</style>
@{
    var eleId = TempData["eleId"];
    var read = Convert.ToBoolean(TempData["readOnly"]);
    var refGuidId = TempData["refGuidId"];
    var fileGuidId = TempData["fileGuidId"];

}
@foreach (var item in Model)
{
    var idImg = $"desimg{eleId}" + i;
    var inputId = $"txtNameimg{eleId}" + i;
    var pic = item?.RowGuid != null ? item?.Filename : "รูปที่ " + i;
    if (item?.RowGuid != null)
    {
        <div class="col-sm-3 col-6 p-2" id="@idImg">
            <div class="img-wrapper">
                <div class="imgplace  @(item?.RowGuid != null ? "showimg":"") ">
                    <input type="hidden" name="@refGuidId" value="@item.RowGuid" />
                    <img src="@Url.Action("ViewAttachFileImage", "AttachFile", new { @id = item.RowGuid, refTable=item.ReferenceTable, refCmp=item.ReferenceGroup })" class="pointer" onclick="window.open('@Url.Action("ViewAttachFileImage", "AttachFile", new { @id = item.RowGuid, refTable=item.ReferenceTable, refCmp=item.ReferenceGroup })', '_blank');" />
                    @if (read == null || read == false)
                    {
                        <a href="javascript:;" class="img-delete" onclick="Swal.fire({title: 'ต้องการลบไฟล์ ใช่หรือไม่?',icon: 'info',showDenyButton: true,confirmButtonText: 'ตกลง',denyButtonText: `ยกเลิก`,}).then((result) => {if (result.isConfirmed) {showWait();deleteImageList('@idImg','@item.RowGuid');}});"><i class="fa fa-trash text-danger"></i></a>
                    }

                </div>
            </div>
            <input name="imageName" id="@inputId" class="form-control form-control-sm text-center img-wrapper-filename" value="@item.Filename" readonly />
        </div>

    }
    else
    {
        <div class="col-sm-3 col-6 p-2 " id="@idImg">
            <div class="img-wrapper ">
                <h4 class="placeholder">คลิกเพื่ออัพโหลด</h4>
                <div class="imgplace @(item?.RowGuid != null ? "showimg":"") ">
                    @if (item?.RowGuid != null)
                    {
                        <input type="hidden" name="@refGuidId" value="@item.RowGuid" />
                        <img src="@Url.Action("ViewAttachFileImage", "AttachFile", new { @id = item.RowGuid, refTable=item.ReferenceTable, refCmp=item.ReferenceGroup })" />
                        <a href="javascript:;" class="img-delete" onclick="Swal.fire({title: 'ต้องการลบไฟล์ ใช่หรือไม่?',icon: 'info',showDenyButton: true,confirmButtonText: 'ตกลง',denyButtonText: `ยกเลิก`,}).then((result) => {if (result.isConfirmed) {showWait();deleteImageList('@idImg','@item.RowGuid');}});"><i class="fa fa-trash text-danger"></i></a>

                    }
                </div>
            </div>
            <input name="imageName" id="@inputId" class="form-control form-control-sm text-center img-wrapper-filename" value="@pic" />
        </div>
        <script>
            initImageDropArea('@idImg', '@eleId', '@TempData["refId"]', '@TempData["refGuidId"]', '@TempData["fileGuidId"]', '@TempData["refTable"]', '@TempData["refCmp"]', '@read');

        </script>

    }
    i++;
}

@if (read == null || read == false)
{
    <div class="col-sm-3 col-6 p-2">
        <div class="img-wrapper">
            <div class="placeholder" id="@eleId" onclick="addImgInDiv(this)"><h4>+ เพิ่มรูป</h4> </div>
        </div>
    </div>
}

<script>
    var refId = @TempData["refId"];
    var refGuidId = '@TempData["refGuidId"]';
    var refTable = '@TempData["refTable"]';
    var refCmp = '@TempData["refCmp"]';
    var read = '@TempData["readOnly"]';

    function addImgInDiv(res) {

        //console.log(res.id);

        var arrImgId = $('input[name="@refGuidId"]').map(function () {
            return this.value;
        }).get();
        var arrImgNameId = $('input[name="imageName"]').map(function () {
            return this.value;
        }).get();

        $.ajax({
            url: "@Url.Action("AddItemImage", "AttachFile")",
            data: {
                fileGuidId: arrImgId,
                imageName: arrImgNameId, refId: refId, refGuidId: refGuidId, refTable: refTable, refCmp: refCmp, eleId: res.id, read: read
            },
            type: "Post",
            success: function (result) {
                $("#" + res.id).empty();
                $("#" + res.id).html(result);
            }
        });
        
    }

     @if (ViewBag.errorAddImg != null)
    {
        <text>
            Swal.fire({
                title: "@ViewBag.errorAddImg",
                icon: "error",
                buttons: "ปิด",
            });
        </text>
    }

</script>